# Network Allocation
server.port=8088

# In-Memory H2 Database Connection Settings
spring.datasource.url=jdbc:h2:mem:analyticsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Enable the Built-in Visual SQL Web Interface
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate SQL Auto-Creation Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
