# Enables the database and saves a file called blogdb inside your user folder
spring.datasource.url=jdbc:h2:file:~/blogdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatically structures SQL tables matching your Java Class structures
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enables a visual browser console to check your database rows manually
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
