# Force the system to use your desired port
server.port=8092

# Enable the built-in visual H2 SQL Console dashboard in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure your internal SQL Connection string parameters
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Show the exact raw SQL queries in your console window for easy debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
