# Force a port change to verify Spring Boot is reading this file
server.port=8080

# Connect to a permanent physical file path on your local computer
spring.datasource.url=jdbc:h2:file:./data/blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Lock down Hibernate configurations to never drop data tables
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

