# Assigning the empty slot in your portfolio matrix
server.port=8089

# Enable visual H2 Database console mapping lookups
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database endpoint configurations
spring.datasource.url=jdbc:h2:mem:parkingdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Schema lifecycle automations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
